---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
  - name: test-build
    image: golang:1.13
    commands:
      - make test
      - make build

trigger:
  branch:
    exclude:
      - master

---
kind: pipeline
name: test-master-go-1-13

platform:
  os: linux
  arch: amd64

steps:
  - name: test-build
    image: golang:1.13
    commands:
      - make test COVERAGE_FILE=coverage.txt
      - make build
    volumes:
      - name: deps
        path: /go

  - name: lint
    image: golang:1.13
    commands:
      - make lint
    volumes:
      - name: deps
        path: /go

  - name: coverage
    image: plugins/codecov
    settings:
      required: true
      token:
        from_secret: codecov_token

volumes:
  - name: deps
    temp: {}

trigger:
  branch:
    - master

---
kind: pipeline
name: test-master-go-1-12

platform:
  os: linux
  arch: amd64

steps:
  - name: test-build
    image: golang:1.12
    commands:
      - make test
      - make build

trigger:
  branch:
    - master

---
kind: signature
hmac: a43206f48694a7bc70f9aeaac516f7ca71ce7bd28fe04ad23cb3d4fbea273081

...
